// <auto-generated />
using Agify.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agify.DAL.Migrations
{
    [DbContext(typeof(AgifyDbContext))]
    [Migration("20230106104819_user_id")]
    partial class user_id
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("FE_Sequence");

            modelBuilder.Entity("Agify.Domain.Entities.User", b =>
                {
                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Count")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEXT VALUE FOR FE_Sequence");

                    b.Property<string>("StageOfLife")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Age");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
