version: '3.4'

services:
    agify.api:
        build:
          context: .
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ASPNETCORE_URLS=https://+:443;http://+:80
           - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
           - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Agify.API.pfx
        volumes:
           - ~/.aspnet/https:/https:ro
        ports:
           - "5000:80"
           - "5001:443"     
        depends_on:
           - sqldb 
           - redis

    sqldb:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
           - "1450:1433"
        environment:
           SA_PASSWORD: "guclusifreguclubeyin"
           ACCEPT_EULA: "Y"

    redis:
        image: redis:latest
        ports:
            - 6379:6379