version: '3.4'

services:
    agify.api:
        build:
          context: .
        ports:
           - "5000:80"
           - "5001:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:5001;http://+:5000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55w0rd!
            - ASPNETCORE_Kestrel__Certificates__Default__Path=C:\Users\SIA-OF1\.aspnet\httpsAgify.API.pfx
        volumes:
           - ${USERPROFILE}\.aspnet\https:/.aspnet/https/        
        depends_on:
           - sqldb 

    sqldb:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
           - "1450:1433"
        environment:
           SA_PASSWORD: "guclusifreguclubeyin"
           ACCEPT_EULA: "Y"